gui:
  # fix colors for selected line
  theme:
    selectedLineBgColor:
      - reverse # set to `default` to have no background colour
      - bold
    selectedRangeBgColor:
      - reverse
os:
  # source: https://github.com/LazyVim/LazyVim/discussions/543#discussioncomment-5808573
  edit: "nvim --server $NVIM --remote-tab {{filename}}"
git:
  paging:
    colorArg: always
    useConfig: true
customCommands:
  - key: "<c-d>"
    description: "Reset to the remote branch"
    command: echo 'git reset --hard origin/{{.CheckedOutBranch.Name}}'
    context: files
    prompts:
      - type: confirm
        title: "Action: git reset --hard origin/{{.CheckedOutBranch.Name}}"
        body: "Are you sure you want to reset to the remote branch?"
