gui:
  # fix colors for selected line
  theme:
    selectedLineBgColor:
      - reverse # set to `default` to have no background colour
      - bold
os:
  # source: https://github.com/LazyVim/LazyVim/discussions/543#discussioncomment-5808573
  edit: "nvim --server $NVIM --remote-tab {{filename}}"
git:
  overrideGpg: true
  paging:
    colorArg: always
    useConfig: true
services:
  "gitlab.ataccama.dev": "gitlab:gitlab.ataccama.dev"
customCommands:
  # - key: <c-f>
  #   description: Fetch branch
  #   context: localBranches
  #   command: git fetch origin {{.SelectedLocalBranch.Name}}:{{.SelectedLocalBranch.Name}}
  - key: "<c-b>"
    description: "Rebase --keep-base"
    context: localBranches
    command: git rebase --keep-base {{.SelectedLocalBranch.Name}}
    prompts:
      - type: confirm
        title: Rebase on {{.SelectedLocalBranch.Name}}
        body: "Are you sure you want to execute: git rebase --keep-base {{.SelectedLocalBranch.Name}}?"
  - key: "<c-n>"
    description: "Commit --no-verify"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: commits
    subprocess: true
  - key: "<c-d>"
    description: "Reset to the remote branch"
    command: "git reset --hard origin/{{.CheckedOutBranch.Name}}"
    context: files
    prompts:
      - type: confirm
        title: "Action: git reset --hard origin/{{.CheckedOutBranch.Name}}"
        body: "Are you sure you want to reset to the remote branch?"
  - key: "<c-d>"
    description: "Trims your tracking branches whose upstream branches are merged or stray"
    command: "git trim --no-confirm"
    context: localBranches
    prompts:
      - type: confirm
        title: "Trims your tracking branches whose upstream branches are merged or stray"
        body: "Are you sure you want to delete local branches whose upstream branches are merged or stray?"
    stream: true
  - key: "<c-u>"
    description: "Force push all branches in your current stack"
    context: global
    command: git fpstack
    prompts:
      - type: confirm
        title: Sending git fpstack
        body: Are you sure you want to push all branches in your current stack?
    stream: true
