gui:
  # fix colors for selected line
  theme:
    selectedLineBgColor:
      - reverse # set to `default` to have no background colour
      - bold
    selectedRangeBgColor:
      - reverse
os:
  # source: https://github.com/LazyVim/LazyVim/discussions/543#discussioncomment-5808573
  edit: "nvim --server $NVIM --remote-tab {{filename}}"
