k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /Users/Matej.Bransky/Documents/k9s
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    skin: onedark
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreen: false
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  # currentContext: ondemand
  # currentCluster: ondemand
  # clusters:
  #   ondemand:
  #     namespace:
  #       active: matej-bransky
  #       lockFavorites: false
  #       favorites:
  #         - miroslav-rezac
  #         - martin-rubas
  #         - mdm-master
  #         - all
  #         - matej-bransky
  #         - michal-formanek
  #         - default
  #     view:
  #       active: pod
  #     featureGates:
  #       nodeShell: false
  #     shellPod:
  #       image: busybox:1.35.0
  #       command: []
  #       args: []
  #       namespace: default
  #       limits:
  #         cpu: 100m
  #         memory: 100Mi
  #       labels: {}
  #     portForwardAddress: localhost
